### ISSUE TITLE
Extra margin on navbar, bootstrap 4 instead of 3

### ISSUE THREAD

**Issue by MiguelDP4** [Angelesh1995/Capstone-Project#1]
- Modify the default bootstrap navbar if you don't want it to have a margin. Add the class on your css giving it margin 0 and the margin will disappear.
- Change the link for the bootstrap css, as you are using bootstrap 4 classes with bootstrap 3.

**Comment by Angelesh1995** [comment]
Thank you. I fixed the mistakes.
